services:
  adaptive:
    image: brean/adaptive_anomaly_detection:ubuntu24.04
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./scripts:/app/scripts/:rw
      - ./data:/data:rw