services:
  adaptive_anomaly_detection:
    image: brean/adaptive_anomaly_detection:ubuntu24.04
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./scripts:/ws/scripts/:rw
      - ./data:/ws/data:rw
      - ./README.md:/ws/README.md:rw